; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc1-n16r8]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
;board = esp32-s3-devkitc1-n8r2
board = esp32-s3-devkitc1-n16r8
;board = waveshare_esp32_s3_zero
;debug_tool = esp-builtin
;upload_protocol = esp-builtin
;build_type = debug            ; ensures debug symbols are included
;debug_init_break = break setup ; Optional: breaks at the start of setup()
framework = arduino
board_build.partitions = partitions_custom.csv
board_build.filesystem = spiffs
monitor_speed = 115200
lib_deps =
  https://github.com/pschatzmann/arduino-audio-tools.git
  https://github.com/pschatzmann/arduino-flite.git
  Adafruit Unified Sensor
  Adafruit NeoPixel
build_flags = 
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
  -DBOARD_HAS_PSRAM
  -O3
